### ISSUE TITLE
#TK01 Crear DER para documentar las tablas en la DB.

### ISSUE THREAD

**Issue by BraianOviedo** [GardeningFriendTeam/GardeningFriendApp#22]

**Comment by mariquenaallosa** [comment]
Ubicado en la rama Main en la carpeta de Documetación 
**959e7cf09b683b221f29fe762b78fe8ee4679226**
![DER](https://github.com/GardeningFriendTeam/GardeningFriendApp/assets/99567012/2b23224a-1650-44b4-ac36-4e87380c29ec)
